// tslint:disable
/**
 * Chabloom Payments
 * Chabloom Payments v1 API
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Observable } from 'rxjs';
import { BaseAPI, HttpHeaders, throwIfNullOrUndefined, encodeURI, OperationOpts, RawAjaxResponse } from '../runtime';
import {
    BillViewModel,
    ProblemDetails,
} from '../models';

export interface ApiBillsIdGetRequest {
    id: string;
}

export interface ApiBillsIdPutRequest {
    id: string;
    billViewModel?: BillViewModel;
}

export interface ApiBillsPostRequest {
    billViewModel?: BillViewModel;
}

/**
 * no description
 */
export class BillsApi extends BaseAPI {

    /**
     */
    apiBillsGet(): Observable<Array<BillViewModel>>
    apiBillsGet(opts?: OperationOpts): Observable<RawAjaxResponse<Array<BillViewModel>>>
    apiBillsGet(opts?: OperationOpts): Observable<Array<BillViewModel> | RawAjaxResponse<Array<BillViewModel>>> {
        return this.request<Array<BillViewModel>>({
            url: '/api/Bills',
            method: 'GET',
        }, opts?.responseOpts);
    };

    /**
     */
    apiBillsIdGet({ id }: ApiBillsIdGetRequest): Observable<BillViewModel>
    apiBillsIdGet({ id }: ApiBillsIdGetRequest, opts?: OperationOpts): Observable<RawAjaxResponse<BillViewModel>>
    apiBillsIdGet({ id }: ApiBillsIdGetRequest, opts?: OperationOpts): Observable<BillViewModel | RawAjaxResponse<BillViewModel>> {
        throwIfNullOrUndefined(id, 'id', 'apiBillsIdGet');

        return this.request<BillViewModel>({
            url: '/api/Bills/{id}'.replace('{id}', encodeURI(id)),
            method: 'GET',
        }, opts?.responseOpts);
    };

    /**
     */
    apiBillsIdPut({ id, billViewModel }: ApiBillsIdPutRequest): Observable<void>
    apiBillsIdPut({ id, billViewModel }: ApiBillsIdPutRequest, opts?: OperationOpts): Observable<void | RawAjaxResponse<void>>
    apiBillsIdPut({ id, billViewModel }: ApiBillsIdPutRequest, opts?: OperationOpts): Observable<void | RawAjaxResponse<void>> {
        throwIfNullOrUndefined(id, 'id', 'apiBillsIdPut');

        const headers: HttpHeaders = {
            'Content-Type': 'application/json',
        };

        return this.request<void>({
            url: '/api/Bills/{id}'.replace('{id}', encodeURI(id)),
            method: 'PUT',
            headers,
            body: billViewModel,
        }, opts?.responseOpts);
    };

    /**
     */
    apiBillsPost({ billViewModel }: ApiBillsPostRequest): Observable<BillViewModel>
    apiBillsPost({ billViewModel }: ApiBillsPostRequest, opts?: OperationOpts): Observable<RawAjaxResponse<BillViewModel>>
    apiBillsPost({ billViewModel }: ApiBillsPostRequest, opts?: OperationOpts): Observable<BillViewModel | RawAjaxResponse<BillViewModel>> {

        const headers: HttpHeaders = {
            'Content-Type': 'application/json',
        };

        return this.request<BillViewModel>({
            url: '/api/Bills',
            method: 'POST',
            headers,
            body: billViewModel,
        }, opts?.responseOpts);
    };

}
