// tslint:disable
/**
 * Chabloom Payments
 * Chabloom Payments v1 API
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Observable } from 'rxjs';
import { BaseAPI, HttpHeaders, throwIfNullOrUndefined, encodeURI, OperationOpts, RawAjaxResponse } from '../runtime';
import {
    BillScheduleViewModel,
    ProblemDetails,
} from '../models';

export interface ApiBillSchedulesIdGetRequest {
    id: string;
}

export interface ApiBillSchedulesIdPutRequest {
    id: string;
    billScheduleViewModel?: BillScheduleViewModel;
}

export interface ApiBillSchedulesPostRequest {
    billScheduleViewModel?: BillScheduleViewModel;
}

/**
 * no description
 */
export class BillSchedulesApi extends BaseAPI {

    /**
     */
    apiBillSchedulesGet(): Observable<Array<BillScheduleViewModel>>
    apiBillSchedulesGet(opts?: OperationOpts): Observable<RawAjaxResponse<Array<BillScheduleViewModel>>>
    apiBillSchedulesGet(opts?: OperationOpts): Observable<Array<BillScheduleViewModel> | RawAjaxResponse<Array<BillScheduleViewModel>>> {
        return this.request<Array<BillScheduleViewModel>>({
            url: '/api/BillSchedules',
            method: 'GET',
        }, opts?.responseOpts);
    };

    /**
     */
    apiBillSchedulesIdGet({ id }: ApiBillSchedulesIdGetRequest): Observable<BillScheduleViewModel>
    apiBillSchedulesIdGet({ id }: ApiBillSchedulesIdGetRequest, opts?: OperationOpts): Observable<RawAjaxResponse<BillScheduleViewModel>>
    apiBillSchedulesIdGet({ id }: ApiBillSchedulesIdGetRequest, opts?: OperationOpts): Observable<BillScheduleViewModel | RawAjaxResponse<BillScheduleViewModel>> {
        throwIfNullOrUndefined(id, 'id', 'apiBillSchedulesIdGet');

        return this.request<BillScheduleViewModel>({
            url: '/api/BillSchedules/{id}'.replace('{id}', encodeURI(id)),
            method: 'GET',
        }, opts?.responseOpts);
    };

    /**
     */
    apiBillSchedulesIdPut({ id, billScheduleViewModel }: ApiBillSchedulesIdPutRequest): Observable<void>
    apiBillSchedulesIdPut({ id, billScheduleViewModel }: ApiBillSchedulesIdPutRequest, opts?: OperationOpts): Observable<void | RawAjaxResponse<void>>
    apiBillSchedulesIdPut({ id, billScheduleViewModel }: ApiBillSchedulesIdPutRequest, opts?: OperationOpts): Observable<void | RawAjaxResponse<void>> {
        throwIfNullOrUndefined(id, 'id', 'apiBillSchedulesIdPut');

        const headers: HttpHeaders = {
            'Content-Type': 'application/json',
        };

        return this.request<void>({
            url: '/api/BillSchedules/{id}'.replace('{id}', encodeURI(id)),
            method: 'PUT',
            headers,
            body: billScheduleViewModel,
        }, opts?.responseOpts);
    };

    /**
     */
    apiBillSchedulesPost({ billScheduleViewModel }: ApiBillSchedulesPostRequest): Observable<BillScheduleViewModel>
    apiBillSchedulesPost({ billScheduleViewModel }: ApiBillSchedulesPostRequest, opts?: OperationOpts): Observable<RawAjaxResponse<BillScheduleViewModel>>
    apiBillSchedulesPost({ billScheduleViewModel }: ApiBillSchedulesPostRequest, opts?: OperationOpts): Observable<BillScheduleViewModel | RawAjaxResponse<BillScheduleViewModel>> {

        const headers: HttpHeaders = {
            'Content-Type': 'application/json',
        };

        return this.request<BillScheduleViewModel>({
            url: '/api/BillSchedules',
            method: 'POST',
            headers,
            body: billScheduleViewModel,
        }, opts?.responseOpts);
    };

}
