// tslint:disable
/**
 * Chabloom Payments
 * Chabloom Payments v1 API
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Observable } from 'rxjs';
import { BaseAPI, HttpHeaders, throwIfNullOrUndefined, encodeURI, OperationOpts, RawAjaxResponse } from '../runtime';
import {
    PaymentScheduleViewModel,
    ProblemDetails,
} from '../models';

export interface ApiPaymentSchedulesIdGetRequest {
    id: string;
}

export interface ApiPaymentSchedulesIdPutRequest {
    id: string;
    paymentScheduleViewModel?: PaymentScheduleViewModel;
}

export interface ApiPaymentSchedulesPostRequest {
    paymentScheduleViewModel?: PaymentScheduleViewModel;
}

/**
 * no description
 */
export class PaymentSchedulesApi extends BaseAPI {

    /**
     */
    apiPaymentSchedulesGet(): Observable<Array<PaymentScheduleViewModel>>
    apiPaymentSchedulesGet(opts?: OperationOpts): Observable<RawAjaxResponse<Array<PaymentScheduleViewModel>>>
    apiPaymentSchedulesGet(opts?: OperationOpts): Observable<Array<PaymentScheduleViewModel> | RawAjaxResponse<Array<PaymentScheduleViewModel>>> {
        return this.request<Array<PaymentScheduleViewModel>>({
            url: '/api/PaymentSchedules',
            method: 'GET',
        }, opts?.responseOpts);
    };

    /**
     */
    apiPaymentSchedulesIdGet({ id }: ApiPaymentSchedulesIdGetRequest): Observable<PaymentScheduleViewModel>
    apiPaymentSchedulesIdGet({ id }: ApiPaymentSchedulesIdGetRequest, opts?: OperationOpts): Observable<RawAjaxResponse<PaymentScheduleViewModel>>
    apiPaymentSchedulesIdGet({ id }: ApiPaymentSchedulesIdGetRequest, opts?: OperationOpts): Observable<PaymentScheduleViewModel | RawAjaxResponse<PaymentScheduleViewModel>> {
        throwIfNullOrUndefined(id, 'id', 'apiPaymentSchedulesIdGet');

        return this.request<PaymentScheduleViewModel>({
            url: '/api/PaymentSchedules/{id}'.replace('{id}', encodeURI(id)),
            method: 'GET',
        }, opts?.responseOpts);
    };

    /**
     */
    apiPaymentSchedulesIdPut({ id, paymentScheduleViewModel }: ApiPaymentSchedulesIdPutRequest): Observable<void>
    apiPaymentSchedulesIdPut({ id, paymentScheduleViewModel }: ApiPaymentSchedulesIdPutRequest, opts?: OperationOpts): Observable<void | RawAjaxResponse<void>>
    apiPaymentSchedulesIdPut({ id, paymentScheduleViewModel }: ApiPaymentSchedulesIdPutRequest, opts?: OperationOpts): Observable<void | RawAjaxResponse<void>> {
        throwIfNullOrUndefined(id, 'id', 'apiPaymentSchedulesIdPut');

        const headers: HttpHeaders = {
            'Content-Type': 'application/json',
        };

        return this.request<void>({
            url: '/api/PaymentSchedules/{id}'.replace('{id}', encodeURI(id)),
            method: 'PUT',
            headers,
            body: paymentScheduleViewModel,
        }, opts?.responseOpts);
    };

    /**
     */
    apiPaymentSchedulesPost({ paymentScheduleViewModel }: ApiPaymentSchedulesPostRequest): Observable<PaymentScheduleViewModel>
    apiPaymentSchedulesPost({ paymentScheduleViewModel }: ApiPaymentSchedulesPostRequest, opts?: OperationOpts): Observable<RawAjaxResponse<PaymentScheduleViewModel>>
    apiPaymentSchedulesPost({ paymentScheduleViewModel }: ApiPaymentSchedulesPostRequest, opts?: OperationOpts): Observable<PaymentScheduleViewModel | RawAjaxResponse<PaymentScheduleViewModel>> {

        const headers: HttpHeaders = {
            'Content-Type': 'application/json',
        };

        return this.request<PaymentScheduleViewModel>({
            url: '/api/PaymentSchedules',
            method: 'POST',
            headers,
            body: paymentScheduleViewModel,
        }, opts?.responseOpts);
    };

}
