// tslint:disable
/**
 * Chabloom Payments
 * Chabloom Payments v1 API
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Observable } from 'rxjs';
import { BaseAPI, HttpHeaders, throwIfNullOrUndefined, encodeURI, OperationOpts, RawAjaxResponse } from '../runtime';
import {
    ProblemDetails,
    TransactionViewModel,
} from '../models';

export interface ApiTransactionsIdGetRequest {
    id: string;
}

export interface ApiTransactionsPostRequest {
    transactionViewModel?: TransactionViewModel;
}

/**
 * no description
 */
export class TransactionsApi extends BaseAPI {

    /**
     */
    apiTransactionsGet(): Observable<Array<TransactionViewModel>>
    apiTransactionsGet(opts?: OperationOpts): Observable<RawAjaxResponse<Array<TransactionViewModel>>>
    apiTransactionsGet(opts?: OperationOpts): Observable<Array<TransactionViewModel> | RawAjaxResponse<Array<TransactionViewModel>>> {
        return this.request<Array<TransactionViewModel>>({
            url: '/api/Transactions',
            method: 'GET',
        }, opts?.responseOpts);
    };

    /**
     */
    apiTransactionsIdGet({ id }: ApiTransactionsIdGetRequest): Observable<TransactionViewModel>
    apiTransactionsIdGet({ id }: ApiTransactionsIdGetRequest, opts?: OperationOpts): Observable<RawAjaxResponse<TransactionViewModel>>
    apiTransactionsIdGet({ id }: ApiTransactionsIdGetRequest, opts?: OperationOpts): Observable<TransactionViewModel | RawAjaxResponse<TransactionViewModel>> {
        throwIfNullOrUndefined(id, 'id', 'apiTransactionsIdGet');

        return this.request<TransactionViewModel>({
            url: '/api/Transactions/{id}'.replace('{id}', encodeURI(id)),
            method: 'GET',
        }, opts?.responseOpts);
    };

    /**
     */
    apiTransactionsPost({ transactionViewModel }: ApiTransactionsPostRequest): Observable<TransactionViewModel>
    apiTransactionsPost({ transactionViewModel }: ApiTransactionsPostRequest, opts?: OperationOpts): Observable<RawAjaxResponse<TransactionViewModel>>
    apiTransactionsPost({ transactionViewModel }: ApiTransactionsPostRequest, opts?: OperationOpts): Observable<TransactionViewModel | RawAjaxResponse<TransactionViewModel>> {

        const headers: HttpHeaders = {
            'Content-Type': 'application/json',
        };

        return this.request<TransactionViewModel>({
            url: '/api/Transactions',
            method: 'POST',
            headers,
            body: transactionViewModel,
        }, opts?.responseOpts);
    };

}
