// tslint:disable
/**
 * Chabloom Payments
 * Chabloom Payments v1 API
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * @export
 * @interface AccountViewModel
 */
export interface AccountViewModel {
    /**
     * @type {string}
     * @memberof AccountViewModel
     */
    id?: string;
    /**
     * @type {string}
     * @memberof AccountViewModel
     */
    name: string;
    /**
     * @type {string}
     * @memberof AccountViewModel
     */
    primaryAddress: string;
    /**
     * @type {string}
     * @memberof AccountViewModel
     */
    externalId: string;
    /**
     * @type {string}
     * @memberof AccountViewModel
     */
    owner?: string | null;
}
