// tslint:disable
/**
 * Chabloom Payments
 * Chabloom Payments v1 API
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * @export
 * @interface AddressViewModel
 */
export interface AddressViewModel {
    /**
     * @type {string}
     * @memberof AddressViewModel
     */
    id?: string;
    /**
     * @type {string}
     * @memberof AddressViewModel
     */
    name: string;
}
