/* tslint:disable */
/* eslint-disable */
/**
 * Chabloom Payments
 * Chabloom Payments v1 API
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface BillTransactionViewModel
 */
export interface BillTransactionViewModel {
    /**
     * 
     * @type {string}
     * @memberof BillTransactionViewModel
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof BillTransactionViewModel
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof BillTransactionViewModel
     */
    externalId: string;
    /**
     * 
     * @type {number}
     * @memberof BillTransactionViewModel
     */
    amount: number;
    /**
     * 
     * @type {string}
     * @memberof BillTransactionViewModel
     */
    bill: string;
}

export function BillTransactionViewModelFromJSON(json: any): BillTransactionViewModel {
    return BillTransactionViewModelFromJSONTyped(json, false);
}

export function BillTransactionViewModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): BillTransactionViewModel {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'name': json['name'],
        'externalId': json['externalId'],
        'amount': json['amount'],
        'bill': json['bill'],
    };
}

export function BillTransactionViewModelToJSON(value?: BillTransactionViewModel | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'name': value.name,
        'externalId': value.externalId,
        'amount': value.amount,
        'bill': value.bill,
    };
}


