// tslint:disable
/**
 * Chabloom Payments
 * Chabloom Payments v1 API
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * @export
 * @interface BillScheduleViewModel
 */
export interface BillScheduleViewModel {
    /**
     * @type {string}
     * @memberof BillScheduleViewModel
     */
    id?: string;
    /**
     * @type {string}
     * @memberof BillScheduleViewModel
     */
    name: string;
    /**
     * @type {number}
     * @memberof BillScheduleViewModel
     */
    amount: number;
    /**
     * @type {number}
     * @memberof BillScheduleViewModel
     */
    dayDue: number;
    /**
     * @type {number}
     * @memberof BillScheduleViewModel
     */
    monthInterval: number;
    /**
     * @type {boolean}
     * @memberof BillScheduleViewModel
     */
    enabled: boolean;
    /**
     * @type {string}
     * @memberof BillScheduleViewModel
     */
    account?: string;
}
