// tslint:disable
/**
 * Chabloom Payments
 * Chabloom Payments v1 API
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * @export
 * @interface BillViewModel
 */
export interface BillViewModel {
    /**
     * @type {string}
     * @memberof BillViewModel
     */
    id?: string;
    /**
     * @type {string}
     * @memberof BillViewModel
     */
    name: string;
    /**
     * @type {number}
     * @memberof BillViewModel
     */
    amount: number;
    /**
     * @type {string}
     * @memberof BillViewModel
     */
    dueDate: string;
    /**
     * @type {string}
     * @memberof BillViewModel
     */
    account?: string;
    /**
     * @type {string}
     * @memberof BillViewModel
     */
    billSchedule?: string;
}
