// tslint:disable
/**
 * Chabloom Payments
 * Chabloom Payments v1 API
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * @export
 * @interface PaymentScheduleViewModel
 */
export interface PaymentScheduleViewModel {
    /**
     * @type {string}
     * @memberof PaymentScheduleViewModel
     */
    id?: string;
    /**
     * @type {string}
     * @memberof PaymentScheduleViewModel
     */
    name: string;
    /**
     * @type {number}
     * @memberof PaymentScheduleViewModel
     */
    amount: number;
    /**
     * @type {number}
     * @memberof PaymentScheduleViewModel
     */
    dayDue: number;
    /**
     * @type {number}
     * @memberof PaymentScheduleViewModel
     */
    interval: number;
}
