/* tslint:disable */
/* eslint-disable */
/**
 * Chabloom Payments
 * Chabloom Payments v1 API
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TenantViewModel
 */
export interface TenantViewModel {
    /**
     * 
     * @type {string}
     * @memberof TenantViewModel
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof TenantViewModel
     */
    name: string;
}

export function TenantViewModelFromJSON(json: any): TenantViewModel {
    return TenantViewModelFromJSONTyped(json, false);
}

export function TenantViewModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): TenantViewModel {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'name': json['name'],
    };
}

export function TenantViewModelToJSON(value?: TenantViewModel | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'name': value.name,
    };
}


