// tslint:disable
/**
 * Chabloom Payments
 * Chabloom Payments v1 API
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * @export
 * @interface TransactionViewModel
 */
export interface TransactionViewModel {
    /**
     * @type {string}
     * @memberof TransactionViewModel
     */
    id?: string;
    /**
     * @type {string}
     * @memberof TransactionViewModel
     */
    name: string;
    /**
     * @type {string}
     * @memberof TransactionViewModel
     */
    externalId: string;
    /**
     * @type {number}
     * @memberof TransactionViewModel
     */
    amount: number;
    /**
     * @type {string}
     * @memberof TransactionViewModel
     */
    account?: string;
    /**
     * @type {string}
     * @memberof TransactionViewModel
     */
    bill?: string;
}
